export { default as SectionFooter } from "./SectionFooter";
export { default as SectionFooterBtn } from "./SectionFooterBtn";
export { default as Feather } from "./Feather";
export { default as WhiteBg } from "./WhiteBg";
export { default as YTVideoBtn } from "./YTVideoBtn";
export { default as NumberInput } from "./NumberInput";
export { default as Loader } from "./Loader";
export { default as Feather2 } from "./Feather2";
export { default as PageRoutes } from "./PageRoutes";
